services:
  - type: web
    name: worm-api
    runtime: python
    repo: https://github.com/nikhil390u8o/WORM
    plan: free
    envVars:
      - key: API_KEY
        sync: false
      - key: MODEL
        value: meta-llama/llama-4-maverick:free
      - key: BASE_URL
        value: https://openrouter.ai/api/v1
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --timeout 60
